version: '3.3'
services:
    asset-cache:
        image: nginx:mainline-alpine
        volumes:
            - ./cache:/data/nginx/cache
            - ./logs:/data/nginx/logs
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/webroot:/data/nginx/webroot:ro
            - ./nginx/localnode.conf:/etc/nginx/templates/localnode.conf.template:ro
        ports:
            - "80:80"
        environment: 
            CACHE_SIZE: 24g
            CACHE_TTL: 1y
            CACHE_INACTIVE_PRUNE_INTERVAL: 15d
            CACHE_UPSTREAM_ENDPOINT: asset-cdn.glb.agni.lindenlab.com
        restart: unless-stopped
        container_name: localnode
        dns: 
            - 8.8.8.8
            - 8.8.4.4