version: '3.4'
services:
    asset-cache:
        image: nginx:mainline-alpine
        volumes:
            - ./cache:/data/nginx/cache
            - ./logs:/data/nginx/logs
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/webroot:/data/nginx/webroot:ro
            - ./nginx/localnode.conf:/etc/nginx/templates/localnode.conf.template:ro
            - ./healthcheck.sh:/data/healthcheck.sh:ro
        ports:
            - "80:80"
        environment: 
            CACHE_SIZE: 24g
            CACHE_TTL: 1y
            CACHE_INACTIVE_PRUNE_INTERVAL: 15d
            CACHE_UPSTREAM_ENDPOINT: asset-cdn.glb.agni.lindenlab.com
            CACHE_LOCAL_ENDPOINT: localnode.local
        restart: unless-stopped
        container_name: localnode
        # Note: This required in the case that you use a custom DNS server, so that the application itself can globally resolve the upstream endpoint
        # You do not need to utilize Google DNS for this, just a resolver that won't cause the container to loopback on itself.
        dns: 
            - 8.8.8.8
            - 8.8.4.4
        healthcheck:
            test: [ "CMD", "sh", "/data/healthcheck.sh" ]
            interval: 1m
            timeout: 5s
            retries: 2
            start_period: 5s
